modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
credits="原作 / Original: 异星之尘 (Aerolite_Dust)"
description='''帕斯特之梦: 重生 — PD社区重制版，经原作者授权。
Community remake of PasterDream, authorized by the original author.

§n致谢 / Acknowledgments:§r
§l原作:§r 异星之尘 (Aerolite_Dust)
§l策划:§r 拭柳喑雨 (ShiLiuYinYu)
§l程序:§r 2884omgpy, ShiLiuYinYu, Garam
§l美术:§r 煮饭婆 (GQ2529), Garam, 小吴 (Vulmoon_XwX)
§l文案:§r 绘星tsuki (Yumihoshi), -北旭- (bei_xu), 爱摸鱼的绫苒 (Akizuki Ayane), 月琴语
§l特别感谢:§r 福米花_flow
'''
logoFile="logo.png"
displayURL="https://www.mcmod.cn/class/28280.html"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    type="required"
    versionRange="[9.5.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    type="required"
    versionRange="[4.9.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="patchouli"
    type="required"
    versionRange="[1.21.1-93,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="[19.51.0.418,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="kubejs"
    type="optional"
    versionRange="[2101.7.2,)"
    ordering="AFTER"
    side="BOTH"
